version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"

  - package-ecosystem: "terraform"
    directory: "/management"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"

  - package-ecosystem: "terraform"
    directory: "/accounts/network-monitor"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
